### ISSUE TITLE
account_info fetch does not work

### ISSUE THREAD

**Issue by nileshtrivedi** [astroband/ruby-stellar-sdk#14]
```
irb> require 'stellar-sdk'
irb> client = Stellar::Client.default_testnet
irb> pubkey = "GAJQ4J2EDDVCBIQIJ5XA2S4UJQKXCHFNOR67AOVQ2YQAVZ42LDLTJN4A"
irb> account = Stellar::Account.from_address(pubkey)
irb> ac_info = client.account_info(account)
```
This returns a `Hyperclient::Link` instance. Calling `_get` on this throws a 404 error (even though the account exists).

```
Faraday::ResourceNotFound (the server responded with status 404)
```

Looks like a case of variable name mismatch:
```
irb> ac_info.inspect
=> #<Hyperclient::Link(account) {"href"=>"https://horizon-testnet.stellar.org/accounts/{account_id}", "templated"=>true}>

irb> ac_info.instance_variable_get("@uri_variables")
=> {:address=>"GAJQ4J2EDDVCBIQIJ5XA2S4UJQKXCHFNOR67AOVQ2YQAVZ42LDLTJN4A"}
```

Notice the difference. The `href` is expecting a variable called `account_id` but `uri_variables` hash contains `address`.

**Comment by nileshtrivedi** [comment]
I get a similar error on `client.send_payment` too.

**Comment by steveklebanoff** [comment]
`send_payment` and `account_info` work if I install the gem from github.  `transactions` did not though, see  https://github.com/stellar/ruby-stellar-sdk/pull/15

**Comment by iamajvillalobos** [comment]
Fix this issue on my PR https://github.com/stellar/ruby-stellar-sdk/pull/21 :)
