### ISSUE TITLE
Faraday::ClientError (the server responded with status 400)

### ISSUE THREAD

**Issue by UmerFrooq** [astroband/ruby-stellar-sdk#199]
#### These are the following step I'm performing and response of each query is 200. 
- keypair = Stellar::KeyPair.random
- account = Stellar::Account.from_address(keypair.address)
- funder = Stellar::Account.from_seed('<my base account secret key>')
- client = Stellar::Client.default
- client.create_account(account: account, funder: funder, starting_balance: 2)
#### I have debug the code from gem and things working fine regardgin params
  def create_account(options = {})
      byebug
      funder = options[:funder]
      sequence = options[:sequence] || (account_info(funder).sequence.to_i + 1)
      # In the future, the fee should be grabbed from the network's last transactions,
      # instead of using a hard-coded default value.
      fee = options[:fee] || DEFAULT_FEE

      payment = Stellar::TransactionBuilder.create_account(
        source_account: funder.keypair,
        sequence_number: sequence,
        base_fee: fee,
        destination: options[:account].keypair,
        starting_balance: options[:starting_balance]
      )
      envelope = payment.to_envelope(funder.keypair)
      submit_transaction(tx_envelope: envelope)
    end
###  Issue occur on submit_transaction(tx_envelope: envelope) evelop have correct data 
any suggestion on this issue.

**Comment by charlie-wasp** [comment]
@UmerFrooq hi! What is exact error message you get? You can get error code like this:

```ruby
begin
# here is your code
rescue => error
  p error # just to get overall representation of error
  p error.response[:body]['extras']['result_codes'] # trying to obtain exact error code
end
```

This will give us something to work on, because just 400 HTTP error is to generic

Btw, all stellar transaction error codes are listed [here](https://developers.stellar.org/api/errors/result-codes/transactions/)

Hope that helps

**Comment by UmerFrooq** [comment]
@charlie-wasp  Hi thanks for quick reply. this is what i'm getting.
transaction"=>"tx_bad_auth"

**Comment by charlie-wasp** [comment]
@UmerFrooq this means that something is wrong with the signature probably. Can you attach the whole code snippet you're running? Also, did you try to build the same transaction using Stellar laboratory?

**Comment by charlie-wasp** [comment]
I am closing this for now due to inactivity. @UmerFrooq feel free to reopen this issue or create a new one if you've got any questions
