### ISSUE TITLE
Should set network for testnet and public net to avoid tx_bad_auth

### ISSUE THREAD

**Issue by steveklebanoff** [astroband/ruby-stellar-sdk#22]
See https://github.com/stellar/ruby-stellar-base/issues/30

If you don't do `Stellar.default_network = Stellar::Networks::PUBLIC`, you will get a `tx_bad_auth` error.

Maybe this library should set `default_network` in the `Stellar::Client.default` and `Stellar::Client.default_testnet` methods

Only reason I could see for _not doing this_, is if you are using the testnet, but want to construct a client for the publicnet but not use it immediately.

**Comment by nullstyle** [comment]
Rather than setting a default network, we should instead raise an appropriate error to tip the developer off that they need to explicitly choose what network to use.

**Comment by JakeUrban** [comment]
If a user initializes a `Stellar::Client` instance for the testnet, any method called on that instance should be for testnet. If the user wants to use mainnet, they should create a client object for mainnet.

I agree with @steveklebanoff 's original idea of setting `default_network` in the `default` and `default_testnet` methods.

**Comment by ire-and-curses** [comment]
For reference, in Go SDK we provided [default clients](https://godoc.org/github.com/stellar/go/clients/horizonclient#pkg-variables) for both public and testnet, but no general default. We wanted to strike a balance between being helpful and forcing the dev to be a little bit explicit.

> var DefaultPublicNetClient = &Client{
>     HorizonURL:     "https://horizon.stellar.org/",
>     HTTP:           http.DefaultClient,
>     horizonTimeOut: HorizonTimeOut,
> }
> 
> DefaultPublicNetClient is a default client to connect to public network.
> 
> var DefaultTestNetClient = &Client{
>     HorizonURL:     "https://horizon-testnet.stellar.org/",
>     HTTP:           http.DefaultClient,
>     horizonTimeOut: HorizonTimeOut,
>     isTestNet:      true,
> }
> 
> DefaultTestNetClient is a default client to connect to test network.

**Comment by ire-and-curses** [comment]
The JS SDK follows a [similar](https://stellar.github.io/js-stellar-sdk/Network.html) approach.

**Comment by abuiles** [comment]
btw, I think we need to update the JS docs, `usePublicNetwork` and
`useTestNetwork` I think is not longer valid, you always have to pass the
network.

**Comment by JakeUrban** [comment]
@abuiles I added you to the PR for this issue. @ire-and-curses you're welcome to take a look as well.

**Comment by JakeUrban** [comment]
We reverted #71 and plan to change the way the network is specified to mirror the other SDKs, namely passing a `network` string to the functions that require it.

**Comment by leighmcculloch** [comment]
We could also add the network passphrase to the options on the client, so that for functions on the client they can just get it out of the client.
