### ISSUE TITLE
How to get the public and secret key strings?

### ISSUE THREAD

**Issue by ulisescarreonalvarez** [astroband/ruby-stellar-sdk#23]
Hi, i new with Stellar on Ruby i know how to use it on python and Node i wanna create an account but need to save the public and secret key on database.

This function give me "GAD4FCA5LB52ANMT7IOOLGSD6UDVE6IQBJKVOYIZCCEMAWSYK2LEM5NT" that i supouse is the public key:

` account = Stellar::Account.random()`

But how i get the secret?

Regards!

**Comment by ramontayag** [comment]
@ulisescarreonalvarez you should look at the `Account` class. I put specs here that illustrate how you can get the secret: https://github.com/stellar/ruby-stellar-sdk/pull/29
