### ISSUE TITLE
Adjust Client.send_payment parameters, remove Stellar::Amount

### ISSUE THREAD

**Issue by fnando** [astroband/ruby-stellar-sdk#45]
As of right now, the contract specified by `Stellar::Client#create_account` requires an integer as the `starting_balance`. This needs to expect `Stellar::Amount` instead, making possible to use `create_account` and `send_payment` interchangeably, after verifying that the account doesn't/does exist.

**Comment by ramontayag** [comment]
I like this, and I also like not having to have extra lines of code in my app to initialize the asset object. Perhaps it can do both?

On a broader note, I've been thinking of making the high-level methods accept an array describing the asset, as well as the asset object itself.

**Comment by JakeUrban** [comment]
After taking look at how `Account.to_payment` interacts with `Stellar::Operation` I think we need to rethink the design altogether. 

`Stellar::Operation.payment`, defined in the base repo, expects an array of different various data types originating from `Account.to_payment`, defined in the SDK repo. This seems like a pretty tight coupling between the two.

I think a better solution would be to:
    - Change the `Stellar::Operation.payment` method's `account` key value to an integer
    - Add an `asset` key to `Stellar::Operation.payment` that accepts an `Stellar::Asset` object
    - Remove the call and definition of `Stellar::Operation.extract_amount` private function
    - Call `Stellar::Operation.interpret_amount` directly from `Stellar::Operation.payment` instead
    - Remove `Stellar::Amount` from the SDK project altogether

This way, the SDK doesn't need to generate the array of values `extract_amount` expects. Adding the `asset` key to the accepted attributes of the `payment` method simplifies the `payment` method and the code the SDK user has to write to create a payment transaction.

**Comment by JakeUrban** [comment]
Just to note, the changes I'm suggesting would mirror the Python SDK, so there is precedent for the changes: https://github.com/StellarCN/py-stellar-base/blob/6d1966752b01df9b01e2a55b3916164bacb38185/stellar_sdk/operation/payment.py#L28

**Comment by JakeUrban** [comment]
All transaction construction methods on the `Client` will be deprecated in favor of using the underlying `Client.horizon` hyperclient. We want to avoid breaking changes as well, so we won't be removing (but potentially deprecating?) the `Amount` class.
