### ISSUE TITLE
Any plans to cut a release soon?

### ISSUE THREAD

**Issue by jimdanz** [astroband/ruby-stellar-sdk#47]
Are there any plans to make a release soon?  I need to pull in the changes from #40 and am hoping not to be on a forked version for too long, so I thought I'd ask.

**Comment by ramontayag** [comment]
Working on one now!

**Comment by bartekn** [comment]
`stellar-sdk@0.6.0` released.

**Comment by jimdanz** [comment]
Awesome, thanks!
