### ISSUE TITLE
RuntimeError: rbnacl-libsodium is not supported by rbnacl 6.0+.

### ISSUE THREAD

**Issue by dusupark1** [astroband/ruby-stellar-sdk#49]
I've installed stellar-sdk and libsodium on Ubuntu 14.04.5 LTS:

$ gem list | grep stellar
stellar-base (0.17.0)
stellar-sdk (0.5.0)
$ sudo apt list --installed | grep sodium

WARNING: apt does not have a stable CLI interface yet. Use with caution in scripts.

libsodium-dev/trusty,now 1.0.3-1chl1-trusty1 amd64 [installed]
libsodium13/trusty,now 1.0.3-1chl1-trusty1 amd64 [installed,automatic]

But I have a run-time error when I require staller-sdk on irb:

$ irb
irb(main):001:0> require 'staller-sdk'
RuntimeError: rbnacl-libsodium is not supported by rbnacl 6.0+. Please remove it as a dependency and install libsodium using your system package manager. See https://github.com/crypto-rb/rbnacl#installation

What shall I do?

**Comment by ramontayag** [comment]
Should be releasing a version that fixes this in the next day or so. [v0.18.0 of stellar-base](https://github.com/stellar/ruby-stellar-base/blob/master/CHANGELOG.md#changed) released, you shouldn't run into this error.

**Comment by bartekn** [comment]
`stellar-sdk@0.6.0` released.
