### ISSUE TITLE
Horizon v.0.18.0 Compatibility

### ISSUE THREAD

**Issue by theaeolianmachine** [astroband/ruby-stellar-sdk#56]
With Horizon v0.18.0, the following breaking changes will occur:

- The `manage_offer` endpoint will be renamed to `manage_sell_offer`
- The `create_passive_offer` endpoint will be renamed to `create_passive_sell_offer`.

We suggest for all Stellar SDK maintainers to offer compatibility between `v.0.17.X` type names as well as the new names in `v.0.18.0` in order to make the transition process from `v0.17.X` to `v0.18.0` to go smoother.

Let me know if you have any questions!

**Comment by theaeolianmachine** [comment]
@ramontayag

**Comment by ramontayag** [comment]
stellar-base v0.20.0 with these changes has been released :+1:
