### ISSUE TITLE
 Support for SEP 10 challenge transaction

### ISSUE THREAD

**Issue by ire-and-curses** [astroband/ruby-stellar-sdk#62]
SEP 10 describes a [specific form](https://github.com/stellar/stellar-protocol/blob/master/ecosystem/sep-0010.md#response) for the "challenge" transaction used for authentication. Providing a helper at the SDK level makes sense to save users from reimplementing the spec.

Here are example implementations in [Go](https://github.com/stellar/go/pull/1468) and [JS](https://github.com/stellar/js-stellar-sdk/pull/375).

**Comment by ramontayag** [comment]
Thanks for the heads up. Will be happy to review accept pull requests for anyone that needs this.

**Comment by jimdanz** [comment]
@ramontayag this can be marked as closed by #65

**Comment by ramontayag** [comment]
Yes thanks @jimdanz
