### ISSUE TITLE
Faraday::ClientError (the server responded with status 400)

### ISSUE THREAD

**Issue by ulisescarreonalvarez** [astroband/ruby-stellar-sdk#63]
Hi everyone, i'm working with a simple app, i have this code on my user creation:
```

    account           = Stellar::Account.random
    self.seed_key     = account.keypair.seed
    self.address_key  = account.keypair.address
    client            = Stellar::Client.default_testnet()
    friendbot         = Stellar::Account.from_seed(account.keypair.seed)
    client.create_account({
      funder:           Stellar::Account.master,
      account:          friendbot,
      starting_balance: 10_000_000 * Stellar::ONE,
      sequence: 1,
    })
```

But when the code runs, this error shows:

`Faraday::ClientError (the server responded with status 400):`

Am i missing something?

Thanks in advance

**Comment by ramontayag** [comment]
I don't think `master` has any funds. You can use the friendbot method to give an account lumens

**Comment by ramontayag** [comment]
Btw there acceptance specs you can follow. They're both documentation and tests 👍

**Comment by ulisescarreonalvarez** [comment]
Yeah, i change the code with:

`client.friendbot(account)`

We want to let the user to create his own assets, so they can use them for transactions.

Reading the documentation on "stellar.toml" o "coin.toml" we wonder if actually for each assets that the user creates, we need to setthing up the toml file?

**Comment by ramontayag** [comment]
The stellar.toml is just for interoperability between Stellar users.
However, you can create and send assets without a stellar.toml.
