### ISSUE TITLE
Remove fee_paid from transaction response

### ISSUE THREAD

**Issue by tamirms** [astroband/ruby-stellar-sdk#66]
The `fee_paid` field in the Horizon transaction response will be removed when [Horizon 0.25](https://github.com/stellar/go/issues/1812) is released.  The `fee_paid` field has been replaced by `max_fee`, which defines the maximum fee the source account is willing to pay, and fee_charged, which defines the fee that was actually paid for a transaction. See CAP-0005 for more information.

**Comment by JakeUrban** [comment]
This involves simply updating the VCR files cached from prior testing calls. No change in functionality.

**Comment by ire-and-curses** [comment]
isn't there anything in the SDK that stores and renders this response and would therefore need to change (maybe not, just asking)?

**Comment by JakeUrban** [comment]
Nope, no mentions of `fee_paid` anywhere in the repo
