### ISSUE TITLE
Discuss Stellar::Client Refactor

### ISSUE THREAD

**Issue by JakeUrban** [astroband/ruby-stellar-sdk#70]
The `Stellar::Client` class is missing an overarching design philosophy. Only about a third of the operations Horizon supports are implemented in the client, it has some utility functions for calling `friendbot` or building a SEP10 challenge transaction, and it has a method returning a `TransactionPage` object for calling the `"next"` page of results for a /transactions call.

@tomerweller feels as though these helper methods for constructing and POSTing transactions to Horizon don't add much value considering their maintenance cost. I think I agree, considering that they're essentially wrappers around `Stellar::Transaction`. 

The SEP10 helper methods are also being moved to a new SEP10 module (see #69).

So, I think we should step back and consider the purpose of this class. From what I can see, its mainly for containing the `@horizon` [Hyperclient](https://github.com/codegram/hyperclient) object, which users can use directly to make calls to Horizon.

We should decide if `Stellar::Client` should be a thin wrapper around the `@horizon` object, or if we should add methods to the class for users to utilize instead of using `@horizon` directly. Right now, its a mix of both.

**Comment by JakeUrban** [comment]
@leighmcculloch @jimdanz, I'm curious about your thoughts on this

**Comment by JakeUrban** [comment]
Personally I think the Python SDK's [TransactionBuilder](https://github.com/StellarCN/py-stellar-base/blob/6d1966752b01df9b01e2a55b3916164bacb38185/stellar_sdk/transaction_builder.py) class is a great design for how to build transactions. `Stellar::Transaction`'s methods right now assume there will be only 1 operation per transaction.

**Comment by leighmcculloch** [comment]
I like the builder pattern too. I think it suits this use case well. The JS SDK also uses it.

**Comment by ire-and-curses** [comment]
Yeah I also :+1: builder pattern. We didn't do this in the Go SDK, reasoning is outlined [here](https://github.com/stellar/go/issues/844#issuecomment-463093543). Basically if you have multiple returns then it's not a good idea. But in Ruby I think it would be nice, and matches JS approach which is great.

**Comment by JakeUrban** [comment]
For clarity, assuming we want to implement the builder pattern, these are the changes I'm suggesting:

- Remove all transaction construction methods from `Stellar::Client`

There are other methods as well, namely `friendbot`, `transactions`, and `account_info`. I think the only one that should remain is `friendbot`. The `@horizon` hyperclient object can be used in place of the other methods.

- Create a `TransactionBuilder` class similar to the JS or Python SDK
- Remove the methods that construct single-operation transactions from `Stellar::Transaction`

The `Stellar::Operation` class should be the only class that has the methods to actually construct these operations. The `TransactionBuilder` methods would call the methods on `Stellar::Operation` and append the returned operations to the list for the transaction.

**Comment by tomerweller** [comment]
Can we avoid removing functions for the sake of backwards compatibility? Maybe add a deprecation warning instead?

**Comment by JakeUrban** [comment]
This SDK is at v0.6.0 and doesn't have nearly the same community usage compared to any of our other SDK's. Its also likely not up-to-date with Horizon 1.0 and could require breaking changes to the XDR definitions to get it there.

So I don't see a strong reason to avoid breaking changes in the library as long as we have a good versioning system and communicate the changes to the strategic partners we know use it.

**Comment by tomerweller** [comment]
I'm aware of at least two major entities using the ruby sdk in critical production environments and I'm sure there are more. We can't dismiss these.
 
Regarding versioning - you're right from the semantical versioning contract perspective. However, there's an implicit (maybe it should be explicit?) contract for a stellar sdk that you get certain ecosystem features for free just by bumping your version. This happens, for example, with every protocol change. 

According to your suggested changes, once protocol 13 comes along the current clients won't be able to just bump a version - they'll need to change their code. That's a problem.

**Comment by tomerweller** [comment]
Another example for a feature that we want existing clients to get without changing their code is [SEP29](https://github.com/stellar/stellar-protocol/blob/master/ecosystem/sep-0029.md).

**Comment by tomerweller** [comment]
By "not removing" these functions I'm talking about maintaining the contract. We can (and probably should) clean up their implementation. The transaction utility functions should definitely switch over to use the new transaction builder.

**Comment by JakeUrban** [comment]
After further discussion we won't be making any breaking changes to `Client` or `Transaction`. However we should make clear in the source code that these functions are depreciated. Adding to the README's and providing examples will also help point users in the right direction.
