### ISSUE TITLE
Add support for CAP-15

### ISSUE THREAD

**Issue by JakeUrban** [astroband/ruby-stellar-sdk#88]
[CAP-15](https://github.com/stellar/stellar-protocol/blob/master/core/cap-0015.md)

See the [cap15-support](https://github.com/stellar/ruby-stellar-base/tree/cap15-support) branch on this repository for a WIP implementation of the changes described below.

Changes needed:
- [x] Update XDR
- [x] Update all references to `TransactionEnvelope` to `TransactionV1Envelope` or find a backwards-compatible fix.
     - CAP-15 changed `TransactionEnvelope` from a `struct` to a `union` and renamed the original definition `TransactionV1Envelope`. Since this class is autogenerated, the ruby class and its attributes will also be changed. We should try to find a fix for this, otherwise the code of anyone who works with these objects will break when they upgrade to the version that includes CAP-15 support.
- [ ] Add helper methods for `FeeBumpTransaction` in `lib/stellar`
    - This class will likely need many of the methods defined on `Transaction`
- [ ] Add helper methods for `FeeBumpTransactionEnvelope` in `lib/stellar`
    - This class will likely need many of the methods defined on `TransactionV1Envelope`

**Comment by JakeUrban** [comment]
@ire-and-curses are the SDK's maintainers aware that CAP-15 introduces the breaking change I outlined regarding `TransactionEnvelope`? I'm not sure if other SDK's use autogenerated code like this, so they might be able to find a backwards-compatible fix more easily.

**Comment by charlie-wasp** [comment]
I believed, it was resolved by #92
